#include "sitkImage.h"
#include "sitkInterpolator.h"
#include "sitkPixelIDValues.h"
#include "sitkDiscreteGaussianImageFilter.h"
#include "sitkBinaryErodeImageFilter.h"
#include "sitkGreaterImageFilter.h"
#include "sitkGreaterEqualImageFilter.h"
#include "sitkLessImageFilter.h"
#include "sitkCastImageFilter.h"
#include "sitkResampleImageFilter.h"
#include "sitkTransform.h"
#include "sitkSignedMaurerDistanceMapImageFilter.h"
#include "sitkPixelIDTypeLists.h"
#include "sitkClampImageFilter.h"
#include "sitkGradientMagnitudeRecursiveGaussianImageFilter.h"
#include "sitkGradientMagnitudeImageFilter.h"
#include "sitkDerivativeImageFilter.h"
#include "sitkLaplacianImageFilter.h"
#include "sitkPowImageFilter.h"
#include "sitkMinimumMaximumImageFilter.h"
#include "sitkSigmoidImageFilter.h"

#include <iostream>
#pragma message("This should appear! :)")